# Generated by Django 5.0.2 on 2024-03-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cqty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cart",
            name="payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cart",
            name="tprice",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
