# Generated by Django 5.0.2 on 2024-03-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_cart_cqty_cart_payment_cart_tprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cprice",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
