# Generated by Django 5.0.2 on 2024-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_cart_cprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ajax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("mobile", models.PositiveBigIntegerField()),
            ],
        ),
    ]
